package com.giraffes.tgbot.entity;

public enum Location {
    BASE,
    PURCHASE,

    SETTINGS,
    WALLET_SETTINGS,
    WALLET_CONFIRMATION,

    AUCTIONS_BROWSE,
    AUCTION_PARTICIPATION,
    AUCTION_REGISTRATION,
    AUCTION_UNSUBSCRIBE,
}
