package com.tgbot.entity;

public enum Location {
    BASE,
    PURCHASE,

    ABOUT_COLLECTION,

    SETTINGS,
    WALLET_SETTINGS,
    WALLET_CONFIRMATION,
    LANGUAGE_CHANGE,

    AUCTIONS_BROWSE,
    AUCTION_PARTICIPATION,
    AUCTION_REGISTRATION,
    AUCTION_UNSUBSCRIBE,
}
