server:
  port: 5000

logging:
  level:
    com:
      giraffes:
        tgbot: ${LOGGING_APP_LEVEL}

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog-master.xml

tg-bot:
  botUserName: ${BOT_USER_NAME}
  botToken: ${BOT_TOKEN}

purchase:
  wallet: ${WALLET_ADDRESS}
  basePrice: ${BASE_NFT_PRICE}
  presalePrice: ${PRESALE_NFT_PRICE}
  presaleQuantity: ${PRESALE_NFT_QUANTITY}

ton-provider:
  url: http://localhost:3001
