datasource:
  url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
  username: sa
  password: sa
  driver: org.h2.Driver

tg-bot:
  botUserName: botUserNameMock
  botToken: botTokenMock

auction:
  wallet:

logging:
  level:
    com:
      tgbot: INFO

spring:
  liquibase:
    change-log: classpath:db/changelog-master.xml

user-wallet:
  confirmation-sum:
  confirmation-wallet:

ton-provider:
  url: http://localhost:3001