datasource:
  url: jdbc:postgresql://localhost:5432/giraffes
  username: postgres
  password: postgres

tg-bot:
  botUserName: grf_nft_test_bot
  botToken: 5189688729:AAFN0jqTcioO5PendAKAilLdLK66VwUiSS8

purchase:
  wallet: EQCijPA3WpE8P1rdYScwCEUslglwiJjTJUid0LM6TYFtRlnE
  basePrice: 10000000000
  presalePrice: 6000000000
  presaleQuantity: 300

logging:
  level:
    com:
      giraffes:
        tgbot: TRACE

user-wallet:
  confirmation-sum: 10000000
  confirmation-wallet: EQCijPA3WpE8P1rdYScwCEUslglwiJjTJUid0LM6TYFtRlnE

ton-provider:
  url: http://localhost:3001