datasource:
  url: jdbc:postgresql://localhost:5432/giraffes
  username: postgres
  password: postgres

tg-bot:
  botUserName: grf_nft_test_bot
  botToken: 5189688729:AAFN0jqTcioO5PendAKAilLdLK66VwUiSS8

auction:
  wallet: EQCijPA3WpE8P1rdYScwCEUslglwiJjTJUid0LM6TYFtRlnE

transactions-update-scheduler:
  enabled: false

logging:
  level:
    com:
      giraffes:
        tgbot: TRACE

user-wallet:
  confirmation-sum: 10000000
  confirmation-wallet: EQCijPA3WpE8P1rdYScwCEUslglwiJjTJUid0LM6TYFtRlnE

ton-provider:
  url: http://localhost:3001