datasource:
  driver: org.postgresql.Driver

server:
  port: 5000

logging:
  level:
    com:
      tgbot: ${LOGGING_APP_LEVEL}

spring:
  datasource:
    hikari:
      maximum-pool-size: 10
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog-master.xml

tg-bot:
  botUserName: ${BOT_USER_NAME}
  botToken: ${BOT_TOKEN}

auction:
  wallet: ${COLLECTION_ADDRESS}

purchase:
  enabled: false
  price: ${BASE_NFT_PRICE}
  wallet: ${COLLECTION_ADDRESS}
  presaleQuantity: ${PRESALE_NFT_QUANTITY}
  linkToMarketplace: ${LINK_TO_MARKETPLACE}

user-wallet:
  confirmation-sum: ${CONFIRMATION_WALLET_SUM}
  confirmation-wallet: ${CONFIRMATION_WALLET}

ton-provider:
  url: ${TON_PROVIDER_URL}

p-cloud:
  api-host: ${P_CLOUD_API_HOST:eapi.pcloud.com}
  access-token: ${P_CLOUD_ACCESS_TOKEN}

nft-owner-changed:
  notification:
    enabled: ${NFT_OWNER_CHANGED_NOTIF_ENABLED:true}

ton:
  url: https://toncenter.com/api/v2/
  api-key:

nft-data-synchronization-scheduler:
  enabled: ${NFT_DATA_SYNC_ENABLED:true}

nft-collection:
  address:

