datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: postgres

tg-bot:
  botUserName:
  botToken:

auction:
  wallet:

purchase:
  wallet:
  price:
  presaleQuantity:

logging:
  level:
    com:
      tgbot: TRACE

user-wallet:
  confirmation-sum:
  confirmation-wallet:

ton-provider:
  url: http://localhost:3001

transactions-update-scheduler:
  enabled: false
