datasource:
  driver: org.postgresql.Driver

server:
  port: 5000

logging:
  level:
    com:
      giraffes:
        tgbot: ${LOGGING_APP_LEVEL}

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog-master.xml

tg-bot:
  botUserName: ${BOT_USER_NAME}
  botToken: ${BOT_TOKEN}

auction:
  wallet: ${AUCTION_ADDRESS}

purchase:
  linkToMarketplace: ${LINK_TO_MARKETPLACE:https://beta.disintar.io/collection/UQBj0sX-_qLFMPEx8KFZWX_aukEzjV7DR_Zai0I-NZ_mn2Yy}

user-wallet:
  confirmation-sum: ${CONFIRMATION_WALLET_SUM}
  confirmation-wallet: ${CONFIRMATION_WALLET}

ton-provider:
  url: ${TON_PROVIDER_URL}

p-cloud:
  api-host: ${P_CLOUD_API_HOST:eapi.pcloud.com}
  access-token: ${P_CLOUD_ACCESS_TOKEN:LSDzZ5QLjde4LwKSZiufur7Z59j9khCj2gyw3Jb7c6EzCjFFFt0V}
