version: "3"

services:
  giraffe-postgres:
    container_name: giraffe-postgres
    image: postgres:14.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: giraffes
      PGDATA: /data/postgres
    volumes:
      - docker-giraffes:/data/postgres
    ports:
      - "5432:5432"
  giraffe-amqp:
    container_name: giraffe-rabbitmq
    image: rabbitmq:3.10.2
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  docker-giraffes:
